"""Set many-to-many relationship

Revision ID: c6d89d3772ff
Revises: 
Create Date: 2024-03-13 12:11:16.303598

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6d89d3772ff'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card_types',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_type', sa.Enum('Artifact', 'Enchantment', 'Creature', 'Instant', 'Sorcery', 'Land', name='cardtype'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('flavor_text', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('mana_cost', sa.Integer(), nullable=True),
    sa.Column('oracle_text', sa.String(), nullable=True),
    sa.Column('rarity', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('card_type_tbl',
    sa.Column('card_id', sa.Integer(), nullable=True),
    sa.Column('card_types_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['cards.id'], ),
    sa.ForeignKeyConstraint(['card_types_id'], ['card_types.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card_type_tbl')
    op.drop_table('cards')
    op.drop_table('card_types')
    # ### end Alembic commands ###
